name: TypeScript

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.ref }}-typescript
    cancel-in-progress: true

jobs:
    type-check:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Setup Node.js and dependencies
              uses: ./.github/action

            - name: Run TypeScript type check
              run: |
                  npx tsc --noEmit
